// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SNSCakeBakery_Service.Data;

#nullable disable

namespace SNSCakeBakery_Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260201220701_DBReset")]
    partial class DBReset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImageType", b =>
                {
                    b.Property<int>("ImageTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IMAGETYPEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageTypeId"));

                    b.Property<string>("ImageTypeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("IMAGETYPENAME");

                    b.HasKey("ImageTypeId")
                        .HasName("PK_IMAGETYPES");

                    b.ToTable("IMAGETYPES");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BASEPRICE");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDAT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISACTIVE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NAME");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTTYPEID");

                    b.HasKey("ProductId")
                        .HasName("PK_PRODUCTS");

                    b.HasIndex("ProductTypeId")
                        .HasDatabaseName("IX_PRODUCTS_PRODUCTTYPEID");

                    b.ToTable("PRODUCTS");
                });

            modelBuilder.Entity("ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IMAGEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DISPLAYORDER");

                    b.Property<int>("ImageTypeId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("IMAGETYPEID");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ISPRIMARY");

                    b.Property<int>("ProductId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PRODUCTID");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STORAGEKEY");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("UPLOADEDAT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ImageId")
                        .HasName("PK_PRODUCTIMAGES");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("IX_PRODUCTIMAGES_PRODUCTID");

                    b.ToTable("PRODUCTIMAGES");
                });

            modelBuilder.Entity("ProductType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TYPEID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPENAME");

                    b.HasKey("TypeId")
                        .HasName("PK_PRODUCTTYPES");

                    b.ToTable("PRODUCTTYPES");
                });

            modelBuilder.Entity("SNSCakeBakery_Service.Models.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ADDRESSID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CITY");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("COUNTRY");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("POSTALCODE");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATE");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STREET");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("UNIT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("USERID");

                    b.HasKey("AddressId")
                        .HasName("PK_ADDRESSES");

                    b.ToTable("ADDRESSES");
                });

            modelBuilder.Entity("SNSCakeBakery_Service.Models.GoogleSyncLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastSynced")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("LASTSYNCED");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUS");

                    b.Property<int>("TotalImported")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("TOTALIMPORTED");

                    b.HasKey("Id")
                        .HasName("PK_GOOGLESYNCLOGS");

                    b.ToTable("GOOGLESYNCLOGS");
                });

            modelBuilder.Entity("SNSCakeBakery_Service.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<string>("CakeType")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CAKETYPE");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDDATE");

                    b.Property<int>("DeliveryAddressID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("DELIVERYADDRESSID");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DELIVERYDATE");

                    b.Property<bool>("DeliveryRequired")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("DELIVERYREQUIRED");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOTES");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("ORDERDATE");

                    b.Property<int>("Quantity")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("QUANTITY");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SIZE");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SOURCE");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("USERID");

                    b.HasKey("Id")
                        .HasName("PK_ORDERS");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ORDERS_USERID");

                    b.ToTable("ORDERS");
                });

            modelBuilder.Entity("SNSCakeBakery_Service.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("NVARCHAR2(36)")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("CREATEDDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("FIREBASEUID");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FIRSTNAME");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LASTNAME");

                    b.HasKey("Id")
                        .HasName("PK_USERS");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("ProductType", null)
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTS_PRODUCTTYPES_PRODUCTTYPEID");
                });

            modelBuilder.Entity("ProductImage", b =>
                {
                    b.HasOne("Product", null)
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCTIMAGES_PRODUCTS_PRODUCTID");
                });

            modelBuilder.Entity("SNSCakeBakery_Service.Models.Order", b =>
                {
                    b.HasOne("SNSCakeBakery_Service.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ORDERS_USERS_USERID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("SNSCakeBakery_Service.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
